In [3]:
import numpy as np
array = np.asarray(
    [
        [100,200,300,200],          # 横线
        [100,71,100,280],           # 竖线
        [41,36,78,210],             # 斜线
        [150,210,150,40],           # 竖线
        [41,55,88,123]              # 斜线
    ]
)
del_lines = []
for i, row in enumerate(array):
    x1, x2, y1, y2 = row
    if (x1 != y1) and (x2 != y2):
        del_lines.append(i)
array = np.delete(array, del_lines, axis=0)
print(array)

[[100 200 300 200]
 [100  71 100 280]
 [150 210 150  40]]


In [25]:
import numpy as np
np.array()



ValueError: could not broadcast input array from shape (4,2) into shape (2,4)

In [5]:
import torch
import numpy as np
a = torch.randint(0, 9, (10,2))
out, inds = torch.max(a, dim=1)
for i, d in enumerate(inds):
    if d is 1:
        out[i] = 2

# torch.where

# np
arr = np.ones(4).reshape(1,4)
arr = np.repeat(arr, 2, axis=0)
arr = np.repeat(arr, 2, axis=0)
x = np.array([  [ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25],
                [27, 22, 23, 24, 25],
                [28, 22, 23, 24, 25],
                [29, 22, 23, 24, 25]])
y = x[0:3, [0,1,0]]
z = x.sum(axis=0)
c = x[0::4]

# np.where
d = np.where(x[:,0]>7)
x = x[d]
print(x)
print('done')

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [27 22 23 24 25]
 [28 22 23 24 25]
 [29 22 23 24 25]]
done
